In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
#import seaborn as sns
import pandas as pd
import sqlite3
import numpy as np
import os

In [2]:
with sqlite3.connect('..\soccer\database.sqlite') as con:
    countries = pd.read_sql_query("SELECT * from Country", con)
    matches = pd.read_sql_query("SELECT * from Match", con)
    leagues = pd.read_sql_query("SELECT * from League", con)
    teams = pd.read_sql_query("SELECT * from Team", con)
    player = pd.read_sql_query("SELECT * from Player", con)
    playerstats = pd.read_sql_query("SELECT * from Player_Stats", con)

In [3]:
matches.columns.values

array(['id', 'country_id', 'league_id', 'season', 'stage', 'date',
       'match_api_id', 'home_team_api_id', 'away_team_api_id',
       'home_team_goal', 'away_team_goal', 'home_player_X1',
       'home_player_X2', 'home_player_X3', 'home_player_X4',
       'home_player_X5', 'home_player_X6', 'home_player_X7',
       'home_player_X8', 'home_player_X9', 'home_player_X10',
       'home_player_X11', 'away_player_X1', 'away_player_X2',
       'away_player_X3', 'away_player_X4', 'away_player_X5',
       'away_player_X6', 'away_player_X7', 'away_player_X8',
       'away_player_X9', 'away_player_X10', 'away_player_X11',
       'home_player_Y1', 'home_player_Y2', 'home_player_Y3',
       'home_player_Y4', 'home_player_Y5', 'home_player_Y6',
       'home_player_Y7', 'home_player_Y8', 'home_player_Y9',
       'home_player_Y10', 'home_player_Y11', 'away_player_Y1',
       'away_player_Y2', 'away_player_Y3', 'away_player_Y4',
       'away_player_Y5', 'away_player_Y6', 'away_player_Y7',
       'away_player_Y8', 'away_player_Y9', 'away_player_Y10',
       'away_player_Y11', 'home_player_1', 'home_player_2',
       'home_player_3', 'home_player_4', 'home_player_5', 'home_player_6',
       'home_player_7', 'home_player_8', 'home_player_9', 'home_player_10',
       'home_player_11', 'away_player_1', 'away_player_2', 'away_player_3',
       'away_player_4', 'away_player_5', 'away_player_6', 'away_player_7',
       'away_player_8', 'away_player_9', 'away_player_10',
       'away_player_11', 'goal', 'shoton', 'shotoff', 'foulcommit', 'card',
       'cross', 'corner', 'possession', 'B365H', 'B365D', 'B365A', 'BWH',
       'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH',
       'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'SJH', 'SJD', 'SJA', 'VCH',
       'VCD', 'VCA', 'GBH', 'GBD', 'GBA', 'BSH', 'BSD', 'BSA'], dtype=object)

In [7]:
matches[['home_team_goal', 'away_team_goal', 'B365H', 'B365D', 'B365A', 'BWH','BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA']]

,home_team_goal,away_team_goal,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA
0,1,1,1.73,3.40,5.00,1.75,3.35,4.20,1.85,3.2,3.50,1.80,3.30,3.75
1,0,0,1.95,3.20,3.60,1.80,3.30,3.95,1.90,3.2,3.50,1.90,3.20,3.50
2,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,0,1.44,3.75,7.50,1.40,4.00,6.80,1.40,3.9,6.00,1.44,3.60,6.50
4,1,3,5.00,3.50,1.65,5.00,3.50,1.60,4.00,3.3,1.70,4.00,3.40,1.72
5,1,1,4.75,3.40,1.67,4.85,3.40,1.65,3.70,3.2,1.80,5.00,3.25,1.62
6,2,2,2.10,3.20,3.30,2.05,3.25,3.15,1.85,3.2,3.50,1.83,3.30,3.60
7,1,2,3.20,3.40,2.20,2.55,3.30,2.40,2.40,3.2,2.40,2.50,3.20,2.50
8,1,0,2.25,3.25,2.88,2.30,3.25,2.70,2.10,3.1,3.00,2.25,3.20,2.75
9,4,1,1.30,5.25,9.50,1.25,5.00,10.00,1.30,4.2,8.00,1.25,4.50,10.00
10,1,2,1.30,5.25,9.50,1.25,5.00,10.00,1.30,4.2,8.00,1.29,4.33,9.00
11,0,2,2.60,3.20,2.50,2.60,3.20,2.40,2.40,3.2,2.40,2.50,3.20,2.50
12,0,0,1.91,3.40,4.00,1.85,3.35,3.80,1.80,3.1,3.80,1.80,3.30,3.75
13,2,2,2.90,3.30,2.38,2.75,3.30,2.25,2.50,3.2,2.30,2.60,3.20,2.38
14,1,2,1.70,3.30,4.50,1.75,3.45,4.00,1.70,3.2,4.20,1.67,3.30,4.50
15,0,1,2.35,3.30,3.00,2.35,3.25,2.70,2.20,3.1,2.80,2.20,3.20,2.80
16,1,3,6.00,3.75,1.57,5.10,3.60,1.55,4.60,3.4,1.60,5.50,3.60,1.50
17,1,3,4.00,3.25,1.83,4.30,3.50,1.68,3.70,3.2,1.80,4.00,3.40,1.73
18,2,3,1.36,4.75,8.50,1.25,5.00,9.00,1.30,4.2,8.00,1.36,4.00,7.00
19,0,0,2.40,3.30,2.90,2.25,3.20,2.80,2.20,3.1,2.80,2.50,3.20,2.50
20,2,2,3.20,3.30,2.25,3.25,3.20,2.10,3.10,3.0,2.10,2.75,3.25,2.20
21,2,0,1.75,3.75,4.33,1.85,3.35,3.65,1.75,3.2,4.00,1.73,3.40,4.00
22,1,1,1.40,4.33,8.00,1.38,4.00,7.20,1.40,3.9,6.00,1.33,4.00,8.00
23,1,2,1.83,3.50,4.20,1.80,3.35,3.90,1.85,3.2,3.50,1.73,3.40,4.00
24,0,0,2.00,3.50,3.60,1.95,3.25,3.40,2.00,3.2,3.10,1.91,3.25,3.40
25,1,0,2.70,3.25,2.60,2.50,3.30,2.45,2.45,3.1,2.45,2.50,3.20,2.50
26,1,3,3.60,3.30,2.05,3.40,3.25,1.95,3.90,3.3,1.75,3.75,3.30,1.80
27,1,1,2.30,3.25,2.90,2.20,3.15,3.00,2.00,3.1,3.20,2.20,3.25,2.75
28,1,1,1.25,5.25,10.00,1.23,5.00,10.00,1.30,4.2,8.00,1.25,4.50,10.00
29,2,2,2.00,3.25,3.50,2.10,3.20,3.20,2.00,3.1,3.20,2.00,3.20,3.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25915,6,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25916,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25917,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25918,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25919,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25920,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25921,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25922,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25923,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25924,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25925,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25926,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25927,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25928,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25929,2,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25930,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25931,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25932,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25933,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25934,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25935,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25936,4,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25937,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25938,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25939,3,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25940,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25941,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25942,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25943,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25944,4,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
countries = countries.set_index('id')
leagues = leagues.set_index('id')
teams = teams.set_index('team_api_id')

In [9]:
def get_two_year(row):
    sub = matches[((matches.home_team == row['home_team']) & (matches.away_team == row['away_team'])) | ((matches.home_team == row['away_team']) & (matches.away_team == row['home_team']))]
    sub2 = sub.sort_values(by = 'date')
    
    sub3 = sub2[sub2['date'] < row['date']]
    home_team = row['home_team']
    away_team = row['away_team']
    home = 0
    away = 0
    for index, row2 in sub3.iterrows():
        winning_team = row2['winner']
        if winning_team == 'home':
            if row2['home_team'] == home_team:
                home += 1
            else:
                away += 1
        if winning_team == 'away':
            if row2['away_team'] == away_team:
                away += 1
            else:
                home += 1
    if (home + away) != 0:
        return home * 1.0 / (home + away) * 1.0
    else:
        if home == 0:
            return 0
        else:
            return 1

In [10]:
sub = matches

In [11]:
def get_winner(row):
    if row['home_team_goal'] > row['away_team_goal']:
        return 'home'
    elif row['home_team_goal'] < row['away_team_goal']:
        return 'away'
    else:
        return 'tie'

matches['country'] = matches['country_id'].map(countries['name'])
matches['league'] = matches['league_id'].map(leagues['name'])
matches['home_team'] = matches['home_team_api_id'].map(teams['team_long_name'])
matches['away_team'] = matches['away_team_api_id'].map(teams['team_long_name'])
matches['winner'] = matches.apply(lambda row: get_winner(row), axis = 1)
matches.head(5)
matches.head(5)

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,GBD,GBA,BSH,BSD,BSA,country,league,home_team,away_team,winner
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,3.25,4.00,1.73,3.40,4.20,Belgium,Belgium Jupiler League,Genk,Beerschot AC,tie
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.25,3.75,1.91,3.25,3.60,Belgium,Belgium Jupiler League,Zulte-Waregem,Lokeren,tie
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,NaN,NaN,NaN,NaN,NaN,Belgium,Belgium Jupiler League,Cercle Bruges,Anderlecht,away
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,3.75,5.50,1.44,3.75,6.50,Belgium,Belgium Jupiler League,Gent,Mons,home
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,3.50,1.65,4.75,3.30,1.67,Belgium,Belgium Jupiler League,FCV Dender EH,Standard Liege,away

In [12]:
copy_main = matches
copy_main['two_year_win_percentage'] = copy_main.apply(lambda row: get_two_year(row), axis = 1)
copy_main.sort_values('date')

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,GBA,BSH,BSD,BSA,country,league,home_team,away_team,winner,two_year_win_percentage
24524,24525,24524,24524,2008/2009,1,2008-07-18 00:00:00,486263,10192,9931,1,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Young Boys,Basel,away,0.000000
24525,24526,24524,24524,2008/2009,1,2008-07-19 00:00:00,486264,9930,10179,3,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Aarau,Sion,home,0.000000
24527,24528,24524,24524,2008/2009,1,2008-07-20 00:00:00,486266,7955,10243,1,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Xamax,FC Zuerich,away,0.000000
24526,24527,24524,24524,2008/2009,1,2008-07-20 00:00:00,486265,10199,9824,1,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Luzern,FC Vaduz,away,0.000000
24580,24581,24524,24524,2008/2009,2,2008-07-23 00:00:00,486269,10243,10199,1,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,FC Zuerich,Luzern,home,0.000000
24579,24580,24524,24524,2008/2009,2,2008-07-23 00:00:00,486268,6493,7955,1,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Bellinzona,Xamax,away,0.000000
24578,24579,24524,24524,2008/2009,2,2008-07-23 00:00:00,486267,9931,9956,1,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Basel,Grasshopper,home,0.000000
24582,24583,24524,24524,2008/2009,2,2008-07-24 00:00:00,486271,9824,9930,0,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,FC Vaduz,Aarau,away,0.000000
24581,24582,24524,24524,2008/2009,2,2008-07-24 00:00:00,486270,10179,10192,2,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Sion,Young Boys,home,0.000000
24634,24635,24524,24524,2008/2009,3,2008-07-26 00:00:00,486273,10199,7955,0,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Luzern,Xamax,away,0.000000
24633,24634,24524,24524,2008/2009,3,2008-07-26 00:00:00,486272,9931,6493,2,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Basel,Bellinzona,home,0.000000
24636,24637,24524,24524,2008/2009,3,2008-07-27 00:00:00,486275,10192,9824,0,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Young Boys,FC Vaduz,tie,0.000000
24635,24636,24524,24524,2008/2009,3,2008-07-27 00:00:00,486274,9930,10243,2,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Aarau,FC Zuerich,home,0.000000
24637,24638,24524,24524,2008/2009,3,2008-07-30 00:00:00,486276,9956,10179,3,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Grasshopper,Sion,home,0.000000
24674,24675,24524,24524,2008/2009,4,2008-08-02 00:00:00,486281,10179,9931,2,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Sion,Basel,home,0.000000
24676,24677,24524,24524,2008/2009,4,2008-08-02 00:00:00,486283,7955,9930,0,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Xamax,Aarau,tie,0.000000
24673,24674,24524,24524,2008/2009,4,2008-08-03 00:00:00,486280,6493,10199,2,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Bellinzona,Luzern,tie,0.000000
24675,24676,24524,24524,2008/2009,4,2008-08-03 00:00:00,486282,9824,9956,1,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,FC Vaduz,Grasshopper,tie,0.000000
24677,24678,24524,24524,2008/2009,4,2008-08-03 00:00:00,486284,10243,10192,2,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,FC Zuerich,Young Boys,home,0.000000
24687,24688,24524,24524,2008/2009,6,2008-08-06 00:00:00,486294,6493,9930,1,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Bellinzona,Aarau,tie,0.000000
15692,15693,15688,15688,2008/2009,1,2008-08-08 00:00:00,506546,2182,8569,2,...,NaN,NaN,NaN,NaN,Poland,Poland Ekstraklasa,Lech Poznan,GKS Belchatow,away,0.000000
15689,15690,15688,15688,2008/2009,1,2008-08-08 00:00:00,506543,8673,2183,2,...,NaN,NaN,NaN,NaN,Poland,Poland Ekstraklasa,Legia Warszawa,Polonia Warsaw,tie,0.000000
15694,15695,15688,15688,2008/2009,1,2008-08-09 00:00:00,506548,8028,2186,2,...,NaN,NaN,NaN,NaN,Poland,Poland Ekstraklasa,Piast Gliwice,Cracovia,home,0.000000
19662,19663,19660,19660,2008/2009,1,2008-08-09 00:00:00,489984,8485,8066,0,...,NaN,NaN,NaN,NaN,Scotland,Scotland Premier League,Aberdeen,Inverness,away,0.000000
4743,4744,4735,4735,2008/2009,1,2008-08-09 00:00:00,483138,9873,9853,1,...,2.90,2.40,2.88,2.88,France,France Ligue 1,Valenciennes,Saint-Etienne,home,0.000000
4742,4743,4735,4735,2008/2009,1,2008-08-09 00:00:00,483137,9874,9855,1,...,4.25,1.83,3.10,4.20,France,France Ligue 1,Sochaux,Grenoble,away,0.000000
4741,4742,4735,4735,2008/2009,1,2008-08-09 00:00:00,483136,9851,8592,4,...,2.60,2.62,3.00,2.50,France,France Ligue 1,Rennes,Marseille,tie,0.000000
4734,4735,4735,4735,2008/2009,1,2008-08-09 00:00:00,483129,8583,9830,2,...,NaN,NaN,NaN,NaN,France,France Ligue 1,Auxerre,Nantes,home,0.000000
19659,19660,19660,19660,2008/2009,1,2008-08-09 00:00:00,489981,8596,8548,0,...,1.50,6.50,3.75,1.44,Scotland,Scotland Premier League,Falkirk,Rangers,away,0.000000
19660,19661,19660,19660,2008/2009,1,2008-08-09 00:00:00,489982,9860,9927,3,...,3.40,2.00,3.25,3.25,Scotland,Scotland Premier League,Hearts,Motherwell,home,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4668,4669,1729,1729,2015/2016,38,2016-05-15 00:00:00,1987601,10261,8586,5,...,NaN,NaN,NaN,NaN,England,England Premier League,Newcastle United,Tottenham,home,0.454545
4666,4667,1729,1729,2015/2016,38,2016-05-15 00:00:00,1987599,8668,9850,3,...,NaN,NaN,NaN,NaN,England,England Premier League,Everton,Norwich,home,0.500000
21444,21445,19660,19660,2015/2016,38,2016-05-15 00:00:00,2216670,8485,8649,0,...,NaN,NaN,NaN,NaN,Scotland,Scotland Premier League,Aberdeen,Ross County,away,0.600000
4669,4670,1729,1729,2015/2016,38,2016-05-15 00:00:00,1987602,8466,9826,4,...,NaN,NaN,NaN,NaN,England,England Premier League,Southampton,Crystal Palace,home,0.800000
13172,13173,10223,10223,2015/2016,38,2016-05-15 00:00:00,2060639,8543,8535,2,...,NaN,NaN,NaN,NaN,Italy,Italy Serie A,Lazio,Fiorentina,away,0.750000
24462,24463,21484,21484,2015/2016,38,2016-05-15 00:00:00,2030537,8370,8581,3,...,NaN,NaN,NaN,NaN,Spain,Spain LIGA BBVA,Rayo Vallecano,Levante,home,0.625000
24460,24461,21484,21484,2015/2016,38,2016-05-15 00:00:00,2030535,9864,8306,4,...,NaN,NaN,NaN,NaN,Spain,Spain LIGA BBVA,Malaga,Las Palmas,home,0.000000
24457,24458,21484,21484,2015/2016,38,2016-05-15 00:00:00,2030532,8558,8372,4,...,NaN,NaN,NaN,NaN,Spain,Spain LIGA BBVA,Espanyol,Eibar,home,0.333333
24456,24457,21484,21484,2015/2016,38,2016-05-15 00:00:00,2030531,8603,8305,2,...,NaN,NaN,NaN,NaN,Spain,Spain LIGA BBVA,Real Betis,Getafe,home,0.400000
24455,24456,21484,21484,2015/2016,38,2016-05-15 00:00:00,2030530,9869,10205,2,...,NaN,NaN,NaN,NaN,Spain,Spain LIGA BBVA,Sporting Gijon,Villarreal,home,0.142857
13169,13170,10223,10223,2015/2016,38,2016-05-15 00:00:00,2060636,10233,8524,1,...,NaN,NaN,NaN,NaN,Italy,Italy Serie A,Genoa,Atalanta,away,0.833333
13170,13171,10223,10223,2015/2016,38,2016-05-15 00:00:00,2060637,8533,9857,0,...,NaN,NaN,NaN,NaN,Italy,Italy Serie A,Chievo,Bologna,tie,0.625000
13171,13172,10223,10223,2015/2016,38,2016-05-15 00:00:00,2060638,8600,208931,1,...,NaN,NaN,NaN,NaN,Italy,Italy Serie A,Udinese,Carpi,away,0.000000
13174,13175,10223,10223,2015/2016,38,2016-05-15 00:00:00,2060641,8540,9876,3,...,NaN,NaN,NaN,NaN,Italy,Italy Serie A,Palermo,Verona,home,0.666667
25902,25903,24524,24524,2015/2016,34,2016-05-16 00:00:00,1992218,10199,9931,4,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Luzern,Basel,home,0.240000
25901,25902,24524,24524,2015/2016,34,2016-05-16 00:00:00,1992217,7896,10192,1,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Lugano,Young Boys,away,0.500000
25900,25901,24524,24524,2015/2016,34,2016-05-16 00:00:00,1992216,9956,9824,1,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Grasshopper,FC Vaduz,away,0.800000
25904,25905,24524,24524,2015/2016,34,2016-05-16 00:00:00,1992220,10191,10179,1,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Thun,Sion,tie,0.500000
25903,25904,24524,24524,2015/2016,34,2016-05-16 00:00:00,1992219,10190,10243,3,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,St. Gallen,FC Zuerich,home,0.352941
4667,4668,1729,1729,2015/2016,38,2016-05-17 00:00:00,1987600,10260,8678,3,...,NaN,NaN,NaN,NaN,England,England Premier League,Manchester United,Bournemouth,home,0.000000
25905,25906,24524,24524,2015/2016,35,2016-05-22 00:00:00,1992221,9956,10191,0,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Grasshopper,Thun,tie,0.437500
25906,25907,24524,24524,2015/2016,35,2016-05-22 00:00:00,1992222,10179,10243,2,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Sion,FC Zuerich,tie,0.363636
25907,25908,24524,24524,2015/2016,35,2016-05-22 00:00:00,1992223,9824,7896,0,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,FC Vaduz,Lugano,tie,0.500000
25908,25909,24524,24524,2015/2016,35,2016-05-22 00:00:00,1992224,10192,9931,2,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Young Boys,Basel,away,0.375000
25909,25910,24524,24524,2015/2016,35,2016-05-22 00:00:00,1992234,10190,10199,1,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,St. Gallen,Luzern,away,0.529412
25910,25911,24524,24524,2015/2016,36,2016-05-25 00:00:00,1992225,9931,9956,0,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Basel,Grasshopper,away,0.600000
25911,25912,24524,24524,2015/2016,36,2016-05-25 00:00:00,1992226,7896,10190,3,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Lugano,St. Gallen,home,0.500000
25912,25913,24524,24524,2015/2016,36,2016-05-25 00:00:00,1992227,10199,10179,2,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Luzern,Sion,tie,0.272727
25913,25914,24524,24524,2015/2016,36,2016-05-25 00:00:00,1992228,10191,10192,0,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,Thun,Young Boys,away,0.333333
25914,25915,24524,24524,2015/2016,36,2016-05-25 00:00:00,1992229,10243,9824,3,...,NaN,NaN,NaN,NaN,Switzerland,Switzerland Super League,FC Zuerich,FC Vaduz,home,1.000000

In [13]:
matches.head()

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,GBA,BSH,BSD,BSA,country,league,home_team,away_team,winner,two_year_win_percentage
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.73,3.40,4.20,Belgium,Belgium Jupiler League,Genk,Beerschot AC,tie,0.0
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.75,1.91,3.25,3.60,Belgium,Belgium Jupiler League,Zulte-Waregem,Lokeren,tie,0.0
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,NaN,NaN,NaN,NaN,Belgium,Belgium Jupiler League,Cercle Bruges,Anderlecht,away,0.0
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,5.50,1.44,3.75,6.50,Belgium,Belgium Jupiler League,Gent,Mons,home,0.0
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.65,4.75,3.30,1.67,Belgium,Belgium Jupiler League,FCV Dender EH,Standard Liege,away,0.0

In [14]:
#Detailed statistics for each match AND betting odds.
#See: https://www.kaggle.com/forums/f/1357/european-soccer-database/t/22394/column-id-meanings-betting-odds-from-the-match-table
matches.head(5)

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,GBA,BSH,BSD,BSA,country,league,home_team,away_team,winner,two_year_win_percentage
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.73,3.40,4.20,Belgium,Belgium Jupiler League,Genk,Beerschot AC,tie,0.0
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.75,1.91,3.25,3.60,Belgium,Belgium Jupiler League,Zulte-Waregem,Lokeren,tie,0.0
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,NaN,NaN,NaN,NaN,Belgium,Belgium Jupiler League,Cercle Bruges,Anderlecht,away,0.0
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,5.50,1.44,3.75,6.50,Belgium,Belgium Jupiler League,Gent,Mons,home,0.0
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.65,4.75,3.30,1.67,Belgium,Belgium Jupiler League,FCV Dender EH,Standard Liege,away,0.0

In [16]:
#List of leagues and their respective country. We may want to limit analysis to a few leagues 
#(i.e. top tier league in England, Germany, France, Italy & Spain)
leagues.head(5)

       country_id                    name
id
1               1  Belgium Jupiler League
1729         1729  England Premier League
4735         4735          France Ligue 1
7775         7775   Germany 1. Bundesliga
10223       10223           Italy Serie A

In [17]:
#List of unique team names
teams.head(5)

             id team_long_name team_short_name
team_api_id
9987          1           Genk             GEN
9993          2   Beerschot AC             BAC
10000         3  Zulte-Waregem             ZUL
9994          4        Lokeren             LOK
9984          5  Cercle Bruges             CEB

In [18]:
#list of unique players and attributes
player.head(5)

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154

In [19]:
"""
Detailed attributes from the EA Sports FIFA video game series. Players stats are updated frequently and paint 
a fairly accurate picture of the player's skillset. Unlike Baseball, soccer doesn't have a lot of consistent statistics to measure 
actual performance on the field, but this is a decent proxy (though obviously subject to the biases of the EA Sports team 
assessing player's ratings)
"""
playerstats.head(5)

,id,player_fifa_api_id,player_api_id,date_stat,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

In [20]:
matches.columns.values

array(['id', 'country_id', 'league_id', 'season', 'stage', 'date',
       'match_api_id', 'home_team_api_id', 'away_team_api_id',
       'home_team_goal', 'away_team_goal', 'home_player_X1',
       'home_player_X2', 'home_player_X3', 'home_player_X4',
       'home_player_X5', 'home_player_X6', 'home_player_X7',
       'home_player_X8', 'home_player_X9', 'home_player_X10',
       'home_player_X11', 'away_player_X1', 'away_player_X2',
       'away_player_X3', 'away_player_X4', 'away_player_X5',
       'away_player_X6', 'away_player_X7', 'away_player_X8',
       'away_player_X9', 'away_player_X10', 'away_player_X11',
       'home_player_Y1', 'home_player_Y2', 'home_player_Y3',
       'home_player_Y4', 'home_player_Y5', 'home_player_Y6',
       'home_player_Y7', 'home_player_Y8', 'home_player_Y9',
       'home_player_Y10', 'home_player_Y11', 'away_player_Y1',
       'away_player_Y2', 'away_player_Y3', 'away_player_Y4',
       'away_player_Y5', 'away_player_Y6', 'away_player_Y7',
       'away_player_Y8', 'away_player_Y9', 'away_player_Y10',
       'away_player_Y11', 'home_player_1', 'home_player_2',
       'home_player_3', 'home_player_4', 'home_player_5', 'home_player_6',
       'home_player_7', 'home_player_8', 'home_player_9', 'home_player_10',
       'home_player_11', 'away_player_1', 'away_player_2', 'away_player_3',
       'away_player_4', 'away_player_5', 'away_player_6', 'away_player_7',
       'away_player_8', 'away_player_9', 'away_player_10',
       'away_player_11', 'goal', 'shoton', 'shotoff', 'foulcommit', 'card',
       'cross', 'corner', 'possession', 'B365H', 'B365D', 'B365A', 'BWH',
       'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH',
       'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'SJH', 'SJD', 'SJA', 'VCH',
       'VCD', 'VCA', 'GBH', 'GBD', 'GBA', 'BSH', 'BSD', 'BSA', 'country',
       'league', 'home_team', 'away_team', 'winner',
       'two_year_win_percentage'], dtype=object)

Potential predictors to use:
1.) Home Team Historic Win % (Last 1 Wk, Last 2 Wks, Last yr, etc...)
2.) Away Team Historic Win % 
3.) Home Total Player Ratings (potentially just use overall and scrap everything else)
4.) Away Total Player Ratings
5.) Historic Matchup Outcomes
6.) Home Field Advantage
7.) Bookie Predictions (?)

Compare Results Again:
1.) Actual Outcomes
2.) Aggregate Bookie Odds

Can possibly eliminate from data:
1.) Formations

In [21]:
################################################## Most recent version

def get_matchup_wins(row):
    sub = matches[((matches.home_team == row['home_team']) & (matches.away_team == row['away_team'])) | ((matches.home_team == row['away_team']) & (matches.away_team == row['home_team']))]
    sub2 = sub.sort_values(by = 'date')
    
    sub3 = sub2[sub2['date'] < row['date']]
    home_team = row['home_team']
    away_team = row['away_team']
    home = 0
    away = 0
    for index, row2 in sub3.iterrows():
        winning_team = row2['winner']
        if winning_team == 'home':
            if row2['home_team'] == home_team:
                home += 1
            else:
                away += 1
        if winning_team == 'away':
            if row2['away_team'] == away_team:
                away += 1
            else:
                home += 1
    if (home + away) != 0:
        return home * 1.0 / (home + away) * 1.0
    else:
        return -1 ###Haven't played each other before

sub = matches[matches['home_team'].isin(['Real Madrid', 'Barcelona'])].sort_values(by = 'date')
sub2 = sub[sub['away_team'].isin(['Real Madrid', 'Barcelona'])].sort_values(by = 'date')
sub2['func2'] = sub2.apply(lambda row: get_matchup_wins(row), axis = 1)
sub2.sort_values('date')

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,BSH,BSD,BSA,country,league,home_team,away_team,winner,two_year_win_percentage,func2
21543,21544,21484,21484,2008/2009,15,2008-12-13 00:00:00,530343,8634,8633,2,...,1.62,3.75,6.00,Spain,Spain LIGA BBVA,Barcelona,Real Madrid,home,0.000000,-1.000000
21759,21760,21484,21484,2008/2009,34,2009-05-02 00:00:00,530640,8633,8634,2,...,2.50,3.40,2.62,Spain,Spain LIGA BBVA,Real Madrid,Barcelona,away,0.000000,0.000000
21899,21900,21484,21484,2009/2010,12,2009-11-29 00:00:00,684766,8634,8633,1,...,1.83,3.60,4.20,Spain,Spain LIGA BBVA,Barcelona,Real Madrid,home,1.000000,1.000000
22109,22110,21484,21484,2009/2010,31,2010-04-10 00:00:00,685104,8633,8634,0,...,2.50,3.50,2.62,Spain,Spain LIGA BBVA,Real Madrid,Barcelona,away,0.000000,0.000000
22286,22287,21484,21484,2010/2011,13,2010-11-29 00:00:00,875704,8634,8633,5,...,2.10,3.60,3.30,Spain,Spain LIGA BBVA,Barcelona,Real Madrid,home,1.000000,1.000000
22496,22497,21484,21484,2010/2011,32,2011-04-16 00:00:00,875970,8633,8634,1,...,2.70,3.50,2.50,Spain,Spain LIGA BBVA,Real Madrid,Barcelona,tie,0.000000,0.000000
22702,22703,21484,21484,2011/2012,16,2011-12-10 00:00:00,1051808,8633,8634,1,...,2.38,3.50,2.88,Spain,Spain LIGA BBVA,Real Madrid,Barcelona,away,0.000000,0.000000
22905,22906,21484,21484,2011/2012,35,2012-04-21 00:00:00,1051981,8634,8633,1,...,1.67,3.75,4.75,Spain,Spain LIGA BBVA,Barcelona,Real Madrid,away,1.000000,1.000000
23361,23362,21484,21484,2012/2013,7,2012-10-07 00:00:00,1260080,8634,8633,2,...,1.85,3.75,4.00,Spain,Spain LIGA BBVA,Barcelona,Real Madrid,tie,0.857143,0.857143
23191,23192,21484,21484,2012/2013,26,2013-03-02 00:00:00,1260112,8633,8634,2,...,3.00,3.50,2.30,Spain,Spain LIGA BBVA,Real Madrid,Barcelona,home,0.142857,0.142857
23399,23400,21484,21484,2013/2014,10,2013-10-26 00:00:00,1505908,8634,8633,2,...,NaN,NaN,NaN,Spain,Spain LIGA BBVA,Barcelona,Real Madrid,home,0.750000,0.750000
23599,23600,21484,21484,2013/2014,29,2014-03-23 00:00:00,1506098,8633,8634,3,...,NaN,NaN,NaN,Spain,Spain LIGA BBVA,Real Madrid,Barcelona,away,0.222222,0.222222
24140,24141,21484,21484,2014/2015,9,2014-10-25 00:00:00,1778121,8633,8634,3,...,NaN,NaN,NaN,Spain,Spain LIGA BBVA,Real Madrid,Barcelona,home,0.200000,0.200000
23970,23971,21484,21484,2014/2015,28,2015-03-22 00:00:00,1778311,8634,8633,2,...,NaN,NaN,NaN,Spain,Spain LIGA BBVA,Barcelona,Real Madrid,home,0.727273,0.727273
24175,24176,21484,21484,2015/2016,12,2015-11-21 00:00:00,2030194,8633,8634,0,...,NaN,NaN,NaN,Spain,Spain LIGA BBVA,Real Madrid,Barcelona,away,0.250000,0.250000
24385,24386,21484,21484,2015/2016,31,2016-04-02 00:00:00,2030460,8634,8633,1,...,NaN,NaN,NaN,Spain,Spain LIGA BBVA,Barcelona,Real Madrid,away,0.769231,0.769231

In [30]:
############################################################################Aggregate Average

def aggregate_home(row):
    row = row.fillna(-1)
    bets = []
    bets.append(row['B365H'])
    bets.append(row['BWH'])
    bets.append(row['IWH'])
    bets.append(row['LBH'])
    bets.append(row['PSH'])
    bets.append(row['WHH'])
    bets.append(row['SJH'])
    bets.append(row['VCH'])
    bets.append(row['GBH'])
    bets.append(row['BSH'])

    counter = 0
    sum_bets = 0
    for item in bets:
        if item != -1:
            counter += 1
            sum_bets += item
    
    if counter == 0:
        return -1
    
    return sum_bets / counter
    
def aggregate_away(row):    
    row = row.fillna(-1)
    bets = []
    bets.append(row['B365A'])
    bets.append(row['BWA'])
    bets.append(row['IWA'])
    bets.append(row['LBA'])
    bets.append(row['PSA'])
    bets.append(row['WHA'])
    bets.append(row['SJA'])
    bets.append(row['VCA'])
    bets.append(row['GBA'])
    bets.append(row['BSA'])

    counter = 0
    sum_bets = 0
    for item in bets:
        if item != -1:
            counter += 1
            sum_bets += item
    
    if counter == 0:
        return -1
    
    return sum_bets / counter




def aggregate_tie(row):    
    row = row.fillna(-1)
    bets = []
    bets.append(row['B365D'])
    bets.append(row['BWD'])
    bets.append(row['IWD'])
    bets.append(row['LBD'])
    bets.append(row['PSD'])
    bets.append(row['WHD'])
    bets.append(row['SJD'])
    bets.append(row['VCD'])
    bets.append(row['GBD'])
    bets.append(row['BSD'])

    counter = 0
    sum_bets = 0
    for item in bets:
        if item != -1:
            counter += 1
            sum_bets += item
            
    if counter == 0:
        return -1    
        
    return sum_bets / counter

def bet_avg_winner(row):
    winner = min(row['home_bet_avg'], row['away_bet_avg'], row['tie_bet_avg'])
    if row['home_bet_avg'] == winner:
        return 'home'
    elif row['away_bet_avg'] == winner:
        return 'away'
    else:
        return 'tie'
    
def correct(row):
    if row['winner'] == row['bet_avg_winner']:
        return 1
    else:
        return 0


    

sub2 = matches.sort_values(by = 'date')
sub2['home_bet_avg'] = sub2.apply(lambda row: aggregate_home(row), axis = 1)
sub2['away_bet_avg'] = sub2.apply(lambda row: aggregate_away(row), axis = 1)
sub2['tie_bet_avg'] = sub2.apply(lambda row: aggregate_tie(row), axis = 1)
sub2['bet_avg_winner'] = sub2.apply(lambda row: bet_avg_winner(row), axis = 1)
sub2.sort_values('date')

sub2 = sub2[sub2['home_bet_avg'] != -1]

sub2['correct'] = sub2.apply(lambda row: correct(row), axis = 1)

sub2[['winner', 'bet_avg_winner', 'correct', 'home_bet_avg', 'away_bet_avg', 'tie_bet_avg', 'B365H', 'B365A', 'B365D','BWH','BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA']]

sub2['correct'].value_counts()

1    11980
0    10512
Name: correct, dtype: int64

In [23]:
sub2[['B365H', 'B365D', 'B365A']].columns.values

array(['B365H', 'B365D', 'B365A'], dtype=object)

In [32]:
def minl(l):
    min_value = min(l)
    return l.index(min_value)

def get_counts(row):
    
    home = 0
    away = 0
    tie = 0
    
    bet_houses = []
    
    row = row.fillna(-1)
    B365 = [row['B365H'], row['B365A'], row['B365D']]
    BW = [row['BWH'], row['BWA'], row['BWD']]
    IW = [row['IWH'], row['IWA'], row['IWD']]
    LB = [row['LBH'], row['LBA'], row['LBD']]
    PS = [row['PSH'], row['PSA'], row['PSD']]
    WH = [row['WHH'], row['WHA'], row['WHD']]
    SJ = [row['SJH'], row['SJA'], row['SJD']]
    VC = [row['VCH'], row['VCA'], row['VCD']]
    GB = [row['GBH'], row['GBA'], row['GBD']]
    BS = [row['BSH'], row['BSA'], row['BSD']]
    
    bet_houses.append(B365)
    bet_houses.append(BW)
    bet_houses.append(IW)
    bet_houses.append(LB)
    bet_houses.append(PS)
    bet_houses.append(WH)
    bet_houses.append(SJ)
    bet_houses.append(VC)
    bet_houses.append(GB)
    bet_houses.append(BS)
    
    for house in bet_houses:
        winner_index = minl(house)
        if winner_index == 0:
            home += 1
        elif winner_index == 1:
            away += 1
        else:
            tie += 1
            
    max_value = max(home, away, tie)
    if tie == max_value:
        return 'tie'
    elif away == max_value:
        return 'away'
    else:
        return 'home'
    
    

    

def correct_count(row):
    if row['winner'] == row['bet_avg_winner_count']:
        return 1
    else:
        return 0
    

sub2 = matches.sort_values(by = 'date')

sub2['bet_avg_winner_count'] = sub2.apply(lambda row: get_counts(row), axis = 1)
sub2.sort_values('date')


sub2['correct_count'] = sub2.apply(lambda row: correct_count(row), axis = 1)

sub2[['winner', 'bet_avg_winner_count', 'correct_count', 'B365H', 'B365A', 'B365D']]

sub2['correct_count'].value_counts()

1    13548
0    12397
Name: correct_count, dtype: int64

In [33]:
len(matches)

25945

In [71]:
def trailing5_home(row):
    team = row['home_team']
    team_df =  matches[((matches.home_team == team) | (matches.away_team == team))]
    team_df = team_df.sort_values(by = 'date')
    team_df = team_df[team_df['date'] < row['date']] 
    if len(team_df) < 5:
        return -1.0
    
    team_df = team_df.tail(5)
    
    wins = 0.0
    losses = 0.0
    
    for index, row2 in team_df.iterrows():
        winning_team = row2['winner']
        if winning_team == 'home':
            if row2['home_team'] == team:
                wins += 1
            else:
                losses += 1
        elif winning_team == 'away':
            if row2['away_team'] == team:
                wins += 1
            else:
                losses += 1
        else:
            wins = wins ###Chuck ties
            
    if wins + losses == 0:
        return -1.0
    else:
        return wins / (wins + losses)
    
    
def trailing5_away(row):
    team = row['away_team']
    team_df =  matches[((matches.home_team == team) | (matches.away_team == team))]
    team_df = team_df.sort_values(by = 'date')
    team_df = team_df[team_df['date'] < row['date']] 
    if len(team_df) < 5:
        return -1.0
    
    team_df = team_df.tail(5)
    
    wins = 0.0
    losses = 0.0
    
    for index, row2 in team_df.iterrows():
        winning_team = row2['winner']
        if winning_team == 'home':
            if row2['home_team'] == team:
                wins += 1
            else:
                losses += 1
        elif winning_team == 'away':
            if row2['away_team'] == team:
                wins += 1
            else:
                losses += 1
        else:
            wins = wins ###Chuck ties
            
    if wins + losses == 0:
        return -1.0
    else:
        return wins / (wins + losses) 



sam = matches[((matches.home_team == 'Sevilla') | (matches.away_team == 'Sevilla'))].sort_values(by = 'date')
sam['trailing5_home'] = sam.apply(lambda row: trailing5_home(row), axis = 1)
sam['trailing5_away'] = sam.apply(lambda row: trailing5_away(row), axis = 1)
sam[['home_team', 'home_team_goal', 'away_team', 'away_team_goal', 'trailing5_home', 'trailing5_away']].head(20)

,home_team,home_team_goal,away_team,away_team_goal,trailing5_home,trailing5_away
21487,Racing Santander,1,Sevilla,1,-1.000000,-1.000000
21596,Sevilla,4,Sporting Gijon,3,-1.000000,-1.000000
21707,Real Betis,0,Sevilla,0,-1.000000,-1.000000
21808,Sevilla,2,Espanyol,0,-1.000000,-1.000000
21819,Atletico Madrid,0,Sevilla,1,-1.000000,-1.000000
21831,Sevilla,4,Athletic Bilbao,0,1.000000,0.333333
21841,Almeria,0,Sevilla,1,0.666667,1.000000
21843,Sevilla,0,Malaga,1,1.000000,0.600000
21855,Valladolid,3,Sevilla,2,0.250000,0.800000
21493,Sevilla,1,Recreativo Huelva,0,0.600000,0.000000
21511,Getafe,0,Sevilla,2,0.333333,0.600000
21516,Sevilla,0,Valencia,0,0.600000,0.500000
21529,Sevilla,0,Barcelona,3,0.500000,1.000000
21541,Real Madrid,3,Sevilla,4,0.500000,0.500000
21550,Sevilla,1,Villarreal,0,0.750000,0.666667
21557,Mallorca,0,Sevilla,0,0.000000,0.750000
21567,Sevilla,1,Osasuna,1,0.666667,0.500000
21582,Deportivo La Coruna,1,Sevilla,3,0.800000,0.666667
21589,Sevilla,1,Numancia,0,1.000000,0.600000
21607,Sevilla,0,Racing Santander,2,1.000000,1.000000

In [66]:
def trailing10_home(row):
    team = row['home_team']
    team_df =  matches[((matches.home_team == team) | (matches.away_team == team))]
    team_df = team_df.sort_values(by = 'date')
    team_df = team_df[team_df['date'] < row['date']] 
    if len(team_df) < 10:
        return -1.0
    
    team_df = team_df.tail(10)
    
    wins = 0.0
    losses = 0.0
    
    for index, row2 in team_df.iterrows():
        winning_team = row2['winner']
        if winning_team == 'home':
            if row2['home_team'] == team:
                wins += 1
            else:
                losses += 1
        elif winning_team == 'away':
            if row2['away_team'] == team:
                wins += 1
            else:
                losses += 1
        else:
            wins = wins ###Chuck ties
            
    if wins + losses == 0:
        return -1.0
    else:
        return wins / (wins + losses) 
    
    
    
    
def trailing10_away(row):
    team = row['away_team']
    team_df =  matches[((matches.home_team == team) | (matches.away_team == team))]
    team_df = team_df.sort_values(by = 'date')
    team_df = team_df[team_df['date'] < row['date']] 
    if len(team_df) < 10:
        return -1.0
    
    team_df = team_df.tail(10)
    
    wins = 0.0
    losses = 0.0
    
    for index, row2 in team_df.iterrows():
        winning_team = row2['winner']
        if winning_team == 'home':
            if row2['home_team'] == team:
                wins += 1
            else:
                losses += 1
        elif winning_team == 'away':
            if row2['away_team'] == team:
                wins += 1
            else:
                losses += 1
        else:
            wins = wins ###Chuck ties
            
    if wins + losses == 0:
        return -1.0
    else:
        return wins / (wins + losses) 



sam = matches[((matches.home_team == 'Barcelona') | (matches.away_team == 'Barcelona'))].sort_values(by = 'date')
sam['trailing10_home'] = sam.apply(lambda row: trailing10_home(row), axis = 1)
sam['trailing10_away'] = sam.apply(lambda row: trailing10_away(row), axis = 1)

sam[['home_team', 'home_team_goal', 'away_team', 'away_team_goal', 'trailing10_home', 'trailing10_away']].tail(20)

,home_team,home_team_goal,away_team,away_team_goal,trailing10_home,trailing10_away
24266,Barcelona,6,Athletic Bilbao,0,1.000000,0.625000
24276,Malaga,1,Barcelona,2,0.571429,1.000000
24285,Barcelona,2,Atletico Madrid,1,1.000000,0.888889
24295,Levante,0,Barcelona,2,0.222222,1.000000
24304,Barcelona,6,Celta Vigo,1,1.000000,0.375000
24217,Sporting Gijon,1,Barcelona,3,0.375000,1.000000
24314,Las Palmas,1,Barcelona,2,0.375000,1.000000
24323,Barcelona,2,Sevilla,1,1.000000,0.833333
24333,Rayo Vallecano,1,Barcelona,5,0.500000,1.000000
24343,Eibar,0,Barcelona,4,0.400000,1.000000
24354,Barcelona,6,Getafe,0,1.000000,0.222222
24374,Villarreal,2,Barcelona,2,0.600000,1.000000
24385,Barcelona,1,Real Madrid,2,1.000000,0.875000
24395,Real Sociedad,1,Barcelona,0,0.625000,0.888889
24406,Barcelona,1,Valencia,2,0.777778,0.400000
24416,Deportivo La Coruna,0,Barcelona,8,0.166667,0.666667
24427,Barcelona,6,Sporting Gijon,0,0.666667,0.285714
24437,Real Betis,0,Barcelona,2,0.500000,0.666667
24448,Barcelona,5,Espanyol,0,0.666667,0.428571
24458,Granada,0,Barcelona,3,0.500000,0.666667